package Hibernate;
// Generated 06/09/2014 17:29:32 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Coletaovos generated by hbm2java
 */
public class Coletaovos  implements java.io.Serializable {


     private Integer codigo;
     private String observacao;
     private Date hora;
     private int ovosInteiros;
     private int ovosQuebrados;
     private int codigoDia;

    public Coletaovos() {
    }

    public Coletaovos(String observacao, Date hora, int ovosInteiros, int ovosQuebrados, int codigoDia) {
       this.observacao = observacao;
       this.hora = hora;
       this.ovosInteiros = ovosInteiros;
       this.ovosQuebrados = ovosQuebrados;
       this.codigoDia = codigoDia;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public int getOvosInteiros() {
        return this.ovosInteiros;
    }
    
    public void setOvosInteiros(int ovosInteiros) {
        this.ovosInteiros = ovosInteiros;
    }
    public int getOvosQuebrados() {
        return this.ovosQuebrados;
    }
    
    public void setOvosQuebrados(int ovosQuebrados) {
        this.ovosQuebrados = ovosQuebrados;
    }
    public int getCodigoDia() {
        return this.codigoDia;
    }
    
    public void setCodigoDia(int codigoDia) {
        this.codigoDia = codigoDia;
    }




}


