package Hibernate;
// Generated 06/09/2014 17:29:32 by Hibernate Tools 3.6.0



/**
 * Gastos generated by hbm2java
 */
public class Gastos  implements java.io.Serializable {


     private Integer codigo;
     private float quantidade;
     private int codigoDia;
     private int codLote;
     private int tipo;

    public Gastos() {
    }

    public Gastos(float quantidade, int codigoDia, int codLote, int tipo) {
       this.quantidade = quantidade;
       this.codigoDia = codigoDia;
       this.codLote = codLote;
       this.tipo = tipo;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public float getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(float quantidade) {
        this.quantidade = quantidade;
    }
    public int getCodigoDia() {
        return this.codigoDia;
    }
    
    public void setCodigoDia(int codigoDia) {
        this.codigoDia = codigoDia;
    }
    public int getCodLote() {
        return this.codLote;
    }
    
    public void setCodLote(int codLote) {
        this.codLote = codLote;
    }
    public int getTipo() {
        return this.tipo;
    }
    
    public void setTipo(int tipo) {
        this.tipo = tipo;
    }




}


