package Hibernate;
// Generated 06/09/2014 17:29:32 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Horasluz generated by hbm2java
 */
public class Horasluz  implements java.io.Serializable {


     private Integer codigo;
     private Date data;
     private int quantidade;

    public Horasluz() {
    }

    public Horasluz(Date data, int quantidade) {
       this.data = data;
       this.quantidade = quantidade;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }




}


