package Hibernate;
// Generated 06/09/2014 17:29:32 by Hibernate Tools 3.6.0



/**
 * Loteeqeletrico generated by hbm2java
 */
public class Loteeqeletrico  implements java.io.Serializable {


     private Integer codigo;
     private int codTipoEqEletrico;
     private float preco;
     private int quantidade;

    public Loteeqeletrico() {
    }

    public Loteeqeletrico(int codTipoEqEletrico, float preco, int quantidade) {
       this.codTipoEqEletrico = codTipoEqEletrico;
       this.preco = preco;
       this.quantidade = quantidade;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public int getCodTipoEqEletrico() {
        return this.codTipoEqEletrico;
    }
    
    public void setCodTipoEqEletrico(int codTipoEqEletrico) {
        this.codTipoEqEletrico = codTipoEqEletrico;
    }
    public float getPreco() {
        return this.preco;
    }
    
    public void setPreco(float preco) {
        this.preco = preco;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }




}


