package Hibernate;
// Generated 06/09/2014 17:29:32 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Lotevacina generated by hbm2java
 */
public class Lotevacina  implements java.io.Serializable {


     private Integer codigo;
     private int codTipoVacina;
     private String fabricante;
     private int quantidade;
     private float preco;
     private float valorTotal;
     private Date validade;

    public Lotevacina() {
    }

    public Lotevacina(int codTipoVacina, String fabricante, int quantidade, float preco, float valorTotal, Date validade) {
       this.codTipoVacina = codTipoVacina;
       this.fabricante = fabricante;
       this.quantidade = quantidade;
       this.preco = preco;
       this.valorTotal = valorTotal;
       this.validade = validade;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public int getCodTipoVacina() {
        return this.codTipoVacina;
    }
    
    public void setCodTipoVacina(int codTipoVacina) {
        this.codTipoVacina = codTipoVacina;
    }
    public String getFabricante() {
        return this.fabricante;
    }
    
    public void setFabricante(String fabricante) {
        this.fabricante = fabricante;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }
    public float getPreco() {
        return this.preco;
    }
    
    public void setPreco(float preco) {
        this.preco = preco;
    }
    public float getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(float valorTotal) {
        this.valorTotal = valorTotal;
    }
    public Date getValidade() {
        return this.validade;
    }
    
    public void setValidade(Date validade) {
        this.validade = validade;
    }




}


