package Hibernate;
// Generated 06/09/2014 17:29:32 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Lote generated by hbm2java
 */
public class Lote  implements java.io.Serializable {


     private Integer codigo;
     private Date dataChegada;
     private int quantInicial;
     private boolean status;
     private float custoAve;
     private float pesoInicial;
     private String origem;
     private String observacao;
     private String tipo;

    public Lote() {
    }

    public Lote(Date dataChegada, int quantInicial, boolean status, float custoAve, float pesoInicial, String origem, String observacao, String tipo) {
       this.dataChegada = dataChegada;
       this.quantInicial = quantInicial;
       this.status = status;
       this.custoAve = custoAve;
       this.pesoInicial = pesoInicial;
       this.origem = origem;
       this.observacao = observacao;
       this.tipo = tipo;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Date getDataChegada() {
        return this.dataChegada;
    }
    
    public void setDataChegada(Date dataChegada) {
        this.dataChegada = dataChegada;
    }
    public int getQuantInicial() {
        return this.quantInicial;
    }
    
    public void setQuantInicial(int quantInicial) {
        this.quantInicial = quantInicial;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public float getCustoAve() {
        return this.custoAve;
    }
    
    public void setCustoAve(float custoAve) {
        this.custoAve = custoAve;
    }
    public float getPesoInicial() {
        return this.pesoInicial;
    }
    
    public void setPesoInicial(float pesoInicial) {
        this.pesoInicial = pesoInicial;
    }
    public String getOrigem() {
        return this.origem;
    }
    
    public void setOrigem(String origem) {
        this.origem = origem;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


