package Hibernate;
// Generated 06/09/2014 17:29:32 by Hibernate Tools 3.6.0



/**
 * Loteracao generated by hbm2java
 */
public class Loteracao  implements java.io.Serializable {


     private Integer codigo;
     private float preco;
     private float quantidade;
     private String fabricante;
     private float valorTotal;
     private int codTipoRacao;

    public Loteracao() {
    }

    public Loteracao(float preco, float quantidade, String fabricante, float valorTotal, int codTipoRacao) {
       this.preco = preco;
       this.quantidade = quantidade;
       this.fabricante = fabricante;
       this.valorTotal = valorTotal;
       this.codTipoRacao = codTipoRacao;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public float getPreco() {
        return this.preco;
    }
    
    public void setPreco(float preco) {
        this.preco = preco;
    }
    public float getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(float quantidade) {
        this.quantidade = quantidade;
    }
    public String getFabricante() {
        return this.fabricante;
    }
    
    public void setFabricante(String fabricante) {
        this.fabricante = fabricante;
    }
    public float getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(float valorTotal) {
        this.valorTotal = valorTotal;
    }
    public int getCodTipoRacao() {
        return this.codTipoRacao;
    }
    
    public void setCodTipoRacao(int codTipoRacao) {
        this.codTipoRacao = codTipoRacao;
    }




}


