package Hibernate;
// Generated 06/09/2014 17:29:32 by Hibernate Tools 3.6.0



/**
 * Mensagemdia generated by hbm2java
 */
public class Mensagemdia  implements java.io.Serializable {


     private MensagemdiaId id;

    public Mensagemdia() {
    }

    public Mensagemdia(MensagemdiaId id) {
       this.id = id;
    }
   
    public MensagemdiaId getId() {
        return this.id;
    }
    
    public void setId(MensagemdiaId id) {
        this.id = id;
    }




}


