package Hibernate;
// Generated 06/09/2014 17:29:32 by Hibernate Tools 3.6.0



/**
 * Mortalidade generated by hbm2java
 */
public class Mortalidade  implements java.io.Serializable {


     private Integer codigo;
     private int quantidade;
     private String observacao;
     private int codTipoMortalidade;
     private int codigoDia;

    public Mortalidade() {
    }

    public Mortalidade(int quantidade, String observacao, int codTipoMortalidade, int codigoDia) {
       this.quantidade = quantidade;
       this.observacao = observacao;
       this.codTipoMortalidade = codTipoMortalidade;
       this.codigoDia = codigoDia;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public int getCodTipoMortalidade() {
        return this.codTipoMortalidade;
    }
    
    public void setCodTipoMortalidade(int codTipoMortalidade) {
        this.codTipoMortalidade = codTipoMortalidade;
    }
    public int getCodigoDia() {
        return this.codigoDia;
    }
    
    public void setCodigoDia(int codigoDia) {
        this.codigoDia = codigoDia;
    }




}


