package Hibernate;
// Generated 06/09/2014 17:29:32 by Hibernate Tools 3.6.0



/**
 * Outrasdespesas generated by hbm2java
 */
public class Outrasdespesas  implements java.io.Serializable {


     private Integer codigo;
     private String descricao;
     private int codGasto;

    public Outrasdespesas() {
    }

    public Outrasdespesas(String descricao, int codGasto) {
       this.descricao = descricao;
       this.codGasto = codGasto;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public int getCodGasto() {
        return this.codGasto;
    }
    
    public void setCodGasto(int codGasto) {
        this.codGasto = codGasto;
    }




}


