package Hibernate;
// Generated 06/09/2014 17:29:32 by Hibernate Tools 3.6.0



/**
 * Salario generated by hbm2java
 */
public class Salario  implements java.io.Serializable {


     private Integer codigo;
     private float preco;
     private int quantidade;
     private float valorTotal;

    public Salario() {
    }

    public Salario(float preco, int quantidade, float valorTotal) {
       this.preco = preco;
       this.quantidade = quantidade;
       this.valorTotal = valorTotal;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public float getPreco() {
        return this.preco;
    }
    
    public void setPreco(float preco) {
        this.preco = preco;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }
    public float getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(float valorTotal) {
        this.valorTotal = valorTotal;
    }




}


