package Hibernate;
// Generated 06/09/2014 17:29:32 by Hibernate Tools 3.6.0



/**
 * Tipopeso generated by hbm2java
 */
public class Tipopeso  implements java.io.Serializable {


     private Integer codigo;
     private float nome;

    public Tipopeso() {
    }

    public Tipopeso(float nome) {
       this.nome = nome;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public float getNome() {
        return this.nome;
    }
    
    public void setNome(float nome) {
        this.nome = nome;
    }




}


