package Hibernate;
// Generated 06/09/2014 17:29:32 by Hibernate Tools 3.6.0



/**
 * Tipomortalidade generated by hbm2java
 */
public class Tipomortalidade  implements java.io.Serializable {


     private Integer codigo;
     private String nome;

    public Tipomortalidade() {
    }

    public Tipomortalidade(String nome) {
       this.nome = nome;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }




}


