package Hibernate;
// Generated 06/09/2014 17:29:32 by Hibernate Tools 3.6.0



/**
 * Tipovacina generated by hbm2java
 */
public class Tipovacina  implements java.io.Serializable {


     private Integer codigo;
     private String nome;
     private String descricao;
     private String via;

    public Tipovacina() {
    }

    public Tipovacina(String nome, String descricao, String via) {
       this.nome = nome;
       this.descricao = descricao;
       this.via = via;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getVia() {
        return this.via;
    }
    
    public void setVia(String via) {
        this.via = via;
    }




}


