package Hibernate;
// Generated 06/09/2014 17:29:32 by Hibernate Tools 3.6.0



/**
 * Tipoeqeletrico generated by hbm2java
 */
public class Tipoeqeletrico  implements java.io.Serializable {


     private Integer codigo;
     private String tipo;
     private String nome;
     private String potencia;

    public Tipoeqeletrico() {
    }

    public Tipoeqeletrico(String tipo, String nome, String potencia) {
       this.tipo = tipo;
       this.nome = nome;
       this.potencia = potencia;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getPotencia() {
        return this.potencia;
    }
    
    public void setPotencia(String potencia) {
        this.potencia = potencia;
    }




}


