package Hibernate;
// Generated 06/09/2014 17:29:32 by Hibernate Tools 3.6.0



/**
 * Valormedio generated by hbm2java
 */
public class Valormedio  implements java.io.Serializable {


     private Integer codigo;
     private String descricao;
     private float valor;

    public Valormedio() {
    }

    public Valormedio(String descricao, float valor) {
       this.descricao = descricao;
       this.valor = valor;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public float getValor() {
        return this.valor;
    }
    
    public void setValor(float valor) {
        this.valor = valor;
    }




}


