package Hibernate;
// Generated 06/09/2014 17:29:32 by Hibernate Tools 3.6.0



/**
 * Venda generated by hbm2java
 */
public class Venda  implements java.io.Serializable {


     private Integer codigo;
     private int quantidade;
     private float valorUnitario;
     private float valorTotal;
     private String destino;
     private String tipo;
     private int codigoDia;

    public Venda() {
    }

    public Venda(int quantidade, float valorUnitario, float valorTotal, String destino, String tipo, int codigoDia) {
       this.quantidade = quantidade;
       this.valorUnitario = valorUnitario;
       this.valorTotal = valorTotal;
       this.destino = destino;
       this.tipo = tipo;
       this.codigoDia = codigoDia;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }
    public float getValorUnitario() {
        return this.valorUnitario;
    }
    
    public void setValorUnitario(float valorUnitario) {
        this.valorUnitario = valorUnitario;
    }
    public float getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(float valorTotal) {
        this.valorTotal = valorTotal;
    }
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public int getCodigoDia() {
        return this.codigoDia;
    }
    
    public void setCodigoDia(int codigoDia) {
        this.codigoDia = codigoDia;
    }




}


